quarkus.mongodb.connection-string=mongodb://gs1dev:admin@localhost:27017
quarkus.mongodb.database=BTpay
quarkus.log.level=DEBUG
quarkus.log.category."org.mongodb".level=INFO
quarkus.log.category."io.netty".level=INFO
quarkus.log.category."org.apache".level=WARN
quarkus.log.category."io.smallrye".level=WARN
quarkus.log.category."com".level=INFO
quarkus.log.category."io".level=INFO
quarkus.log.category."org".level=INFO
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.container-image.group=ro.gs1.dev
quarkus.container-image.name=btmock
quarkus.container-image.tag=latest
quarkus.container-image.registry=dhub.gs1.ro
%dev.quarkus.live-reload.instrumentation=true
quarkus.rest-client.pay-api.url=http://localhost:8080
quarkus.rest-client.pay-api.scope=jakarta.inject.Singleton
jakarta.faces.CLIENT_WINDOW_MODE=none
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true
quarkus.http.proxy.enable-forwarded-prefix=true