quarkus.mongodb.connection-string=mongodb://gs1dev:admin@localhost:27017
quarkus.mongodb.database=BTpay
quarkus.log.level=DEBUG
quarkus.container-image.group=ro.gs1.dev
quarkus.container-image.name=btmock
quarkus.container-image.tag=latest
quarkus.container-image.registry=dhub.gs1.ro